#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.0
#  in conjunction with Tcl version 8.6
#    Jan 03, 2022 11:29:46 PM +0900  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import sakura_window_support

class master:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("580x100+217+213")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("サクラエディタ・タイプ別設定一括コピー")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top
        self.combobox = tk.StringVar()

        self.TLabel1 = ttk.Label(self.top)
        self.TLabel1.place(relx=0.017, rely=0.1, height=19, width=75)
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(text='''設定ファイル名''')

        self.entry_file = ttk.Entry(self.top)
        self.entry_file.place(relx=0.155, rely=0.1, relheight=0.21, relwidth=0.7)

        self.entry_file.configure(state='readonly')
        self.entry_file.configure(cursor="ibeam")

        self.TLabel2 = ttk.Label(self.top)
        self.TLabel2.place(relx=0.017, rely=0.4, height=19, width=68)
        self.TLabel2.configure(background="#d9d9d9")
        self.TLabel2.configure(foreground="#000000")
        self.TLabel2.configure(text='''コピー元タイプ''')

        self.button_select = ttk.Button(self.top)
        self.button_select.place(relx=0.862, rely=0.1, height=25, width=76)
        self.button_select.configure(text='''選択''')

        self.combobox_type = ttk.Combobox(self.top)
        self.combobox_type.place(relx=0.155, rely=0.4, relheight=0.21
                , relwidth=0.695)
        self.combobox_type.configure(textvariable=self.combobox)

        self.button_exec = ttk.Button(self.top)
        self.button_exec.place(relx=0.724, rely=0.7, height=25, width=76)
        self.button_exec.configure(text='''実行''')

        self.button_quit = ttk.Button(self.top)
        self.button_quit.place(relx=0.862, rely=0.7, height=25, width=76)
        self.button_quit.configure(text='''終了''')

def start_up():
    sakura_window_support.main()

if __name__ == '__main__':
    sakura_window_support.main()




